### ISSUE TITLE
shortcut to delete word

### ISSUE THREAD

**Issue by mirsella** [thalesmello/better-ctrlw#2]
hello

i have the habit to delete world with ctrlw, but it was closing my tab :(
now with this extension it just do nothing. which is better, but i want ctrlw to delete world, same as the ctrl+backspace shortcut.

**Comment by mirsella** [comment]
i didn't find a way of simulating keyboard shortcut from a extension

**Comment by mirsella** [comment]
i've tried to make it work with a code found on stack overflow, but it obvioulsy didn't work. i'm a complete noob with chrome extension, and the documentation didn't talk about something like delete word or simulating keyboard shortcut.
thanks

**Comment by landonb** [comment]
@mirsella I realize this is 4 years later, but I ran across your issue, forked this project, and republished the extension with added functionality that can delete back word with whatever keyboard shortcut you want to assign it (because I, too, wanted this feature).

On the Chrome Web Store:
https://chromewebstore.google.com/detail/more-better-ctrl-w/fhgdipcimngeleeemdhkinodbkkmcgjm?pli=1

On GitHub:
https://github.com/tallybark/more-better-ctrlw

With many thanks to @thalesmello for a simple yet wonderful plugin that I've been using for many years!

**Comment by thalesmello** [comment]
@landonb Haha, I love the name of your fork

I'd consider deleting the last word out of the scope of this project because I think that sort of behavior would be better incorporated by AutoHotKey on Windows, and it would work everywhere, even outside of Chrome.

I'm gonna close this issue, as now people have a "more better" option if they need to delete the last word.
